name: 'Publish articles to Qiita'
description: 'Publish articles to Qiita using qiita-cli'

inputs:
  qiita-token:
    required: true
    description: 'Qiita API token'
  github-token:
    required: true
    description: 'GitHub token'
  rootdir:
    required: false
    description: 'Root directory of qiita articles'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install qiita-cli
      run: npm install -g @qiita/qiita-cli@v0.3.0
      shell: bash
    - name: Publish articles
      run: qiita publish --all
      env:
        QIITA_TOKEN: ${{ inputs.qiita-token }}
        QIITA_CLI_ITEMS_ROOT: ${{ inputs.rootdir }}
      shell: bash
    - name: Commit
      run: |
        if [[ -n "${{ inputs.rootdir }}" ]]; then
          git add ${{ inputs.rootdir }}/public/*
        else
          git add public/*
        fi
        if ! git diff --staged --exit-code --quiet; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m '[skip ci] Updated by qiita-cli'
        fi
      shell: bash
    - name: Push
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ inputs.github-token }}
        branch: main
